version: 2

models:

  - name: int_addresses 
    description: Addresses on the platform
    columns: 
      - name: address_uuid
        description: Address Unique Identifier
        tests:
          - not_null
          - unique 
      - name: delivery_address
        tests:
          - not_null
      - name: delivery_zipcode
      - name: delivery_state
      - name: delivery_country
        tests:
          - not_null
  - name: int_orders
    description: Orders on the platform
    columns: 
      - name: order_uuid 
        description: Order Unique Identifier
        tests:
          - not_null
          - unique 
      - name: user_uuid
        description: User Unique Identifier
        tests:
          - not_null
      - name: promo_uuid
        description: Promo Unique Identifier
      - name: address_uuid
        description: Address Unique Identifier
        tests:
          - not_null
      - name: created_at
        tests:
          - not_null
      - name: order_cost
        tests:
          - not_null
      - name: shipping_cost
        tests:
          - not_null
      - name: order_total
        tests:
          - not_null
      - name: tracking_number
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: order_status
        tests:
          - not_null
  - name: int_events
    description: Events from the platform
    columns: 
      - name: event_uuid
        description: Event Unique Identifier
        tests:
          - not_null
          - unique 
      - name: session_uuid
        description: Session Unique Identifier
        tests:
          - not_null
      - name: user_uuid
        description: User Unique Identifier
        tests:
          - not_null
      - name: page_url
        tests:
          - not_null
      - name: order_uuid
      - name: created_at
  - name: int_order_items
    description: Order Items from the platform
    columns: 
      - name: order_uuid
        description: Order Unique Identifier
        tests:
          - not_null
      - name: product_uuid
        description: Product Unique Identifier
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
  - name: int_products
    description: Products
    columns: 
      - name: product_uuid
        description: Product Unique Identifier
        tests:
          - not_null
          - unique  
      - name: product_name
        tests:
          - not_null
      - name: product_price
        tests:
          - not_null
      - name: inventory_amount
        tests:
          - not_null
  - name: int_promos
    description: Promos
    columns: 
      - name: promo_uuid 
        description: Promo Unique Identifier
        tests:
          - not_null
          - unique 
      - name: discount
        tests:
          - not_null
      - name: promo_status
        tests:
          - not_null
  - name: int_users
    description: Users
    columns: 
      - name: user_uuid 
        description: User Unique Identifier
        tests:
          - not_null
          - unique 
      - name: first_name
        tests:
          - not_null
      - name: last_name
        tests:
          - not_null
      - name: email 
        tests:
          - not_null
      - name: phone_number 
      - name: created_at
        tests:
          - not_null
      - name: updated_at
        tests:
          - not_null
      - name: address_uuid
        tests:
          - not_null
